"""
cv_pipeline_demo.py
====================
Demo script: runs the Phase 3 CV pipeline on synthetic fixtures and saves
representative output images and reports to outputs/cv_pipeline_demo/.

PURPOSE: visual verification and pipeline smoke-test.
This is NOT a test (no assertions), NOT a performance benchmark, and
NOT a demonstration of real dataset results — it uses synthetic fixtures
(random-pixel images with fabricated masks) generated by
tests/make_synthetic_fixtures.py.

Usage:
    python -m src.vision.cv_pipeline_demo

Outputs (written to outputs/cv_pipeline_demo/):
    {sid}_raw_rgb.png         — the EXIF-corrected raw image (resized 224x224)
    {sid}_roi_crop.png        — the tight-cropped ROI (before resizing)
    {sid}_roi_normalised.png  — the ROI after CLAHE normalization (resized 224x224)
    {sid}_quality_report.json — per-stage quality check results
    demo_summary.json         — overall summary (accepted/rejected counts, timing)
"""

import json
import logging
import os
import sys
import time

import cv2
import numpy as np

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("cv_pipeline_demo")

# Ensure project root is on sys.path when run as __main__
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(os.path.dirname(_THIS_DIR))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

DEMO_OUT_DIR = os.path.join(_PROJECT_ROOT, "outputs", "cv_pipeline_demo")


def _float_to_uint8(arr: np.ndarray) -> np.ndarray:
    """Convert float32 [0,1] to uint8 [0,255] for saving."""
    return (np.clip(arr, 0.0, 1.0) * 255).astype(np.uint8)


def _save_rgb_png(arr: np.ndarray, path: str) -> None:
    """Save an RGB uint8 array as PNG via OpenCV (converts to BGR)."""
    cv2.imwrite(path, cv2.cvtColor(arr, cv2.COLOR_RGB2BGR))


def run_demo():
    os.makedirs(DEMO_OUT_DIR, exist_ok=True)
    t0 = time.time()

    # --- Build synthetic fixtures ---
    logger.info("Building synthetic fixtures...")
    sys.path.insert(0, os.path.join(_PROJECT_ROOT, "tests"))
    from make_synthetic_fixtures import build_synthetic_fixtures
    raw_dir, _ = build_synthetic_fixtures(force=False)
    logger.info("Synthetic fixture raw dir: %s", raw_dir)

    # --- Import pipeline components ---
    from src.vision.pipeline import process_subject
    from src.vision.roi import MASK_VARIANT_PRIORITY
    from src.data.validation import load_raw_photo

    # --- Discover subjects with both raw and combined mask ---
    subject_pairs = []
    if os.path.isdir(raw_dir):
        for fname in sorted(os.listdir(raw_dir)):
            if fname.endswith("_forniceal_palpebral.png"):
                sid = fname.replace("_forniceal_palpebral.png", "")
                raw_path = os.path.join(raw_dir, f"{sid}.jpg")
                mask_path = os.path.join(raw_dir, fname)
                if os.path.isfile(raw_path):
                    subject_pairs.append((sid, raw_path, mask_path))

    logger.info("Found %d subject(s) with raw + combined mask.", len(subject_pairs))

    summary = {
        "demo_type": "SYNTHETIC_FIXTURES_ONLY — NOT REAL DATA",
        "fixture_dir": raw_dir,
        "subjects_attempted": len(subject_pairs),
        "results": [],
        "accepted": 0,
        "rejected": 0,
    }

    for sid, raw_path, mask_path in subject_pairs:
        logger.info("Processing subject: %s", sid)

        result = process_subject(
            subject_id=sid,
            raw_path=raw_path,
            mask_path=mask_path,
            norm_method="clahe",
            output_size=(224, 224),
        )

        entry = {
            "subject_id": sid,
            "accepted": result.accepted,
            "reject_reason": result.quality_report.get("reject_reason", ""),
            "timing_ms": result.quality_report.get("timing_ms"),
            "raw_quality": None,
            "roi_quality": None,
            "roi_coverage": None,
        }

        if result.quality_report.get("raw_image_quality"):
            entry["raw_quality"] = result.quality_report["raw_image_quality"]
        if result.quality_report.get("roi_quality"):
            entry["roi_quality"] = result.quality_report["roi_quality"]

        if result.accepted:
            summary["accepted"] += 1
            entry["roi_coverage"] = result.roi_info.coverage_fraction

            # Save resized raw image
            raw_out = os.path.join(DEMO_OUT_DIR, f"{sid}_raw_rgb.png")
            _save_rgb_png(_float_to_uint8(result.image_tensor), raw_out)

            # Save ROI crop (before resizing — from roi_info)
            roi_crop_out = os.path.join(DEMO_OUT_DIR, f"{sid}_roi_crop.png")
            _save_rgb_png(result.roi_info.roi_rgb, roi_crop_out)

            # Save normalised ROI (resized 224x224)
            roi_norm_out = os.path.join(DEMO_OUT_DIR, f"{sid}_roi_normalised.png")
            _save_rgb_png(_float_to_uint8(result.roi_tensor), roi_norm_out)

            logger.info(
                "  ✓ Accepted — ROI coverage=%.4f, bbox=%s",
                result.roi_info.coverage_fraction,
                result.roi_info.bbox,
            )
        else:
            summary["rejected"] += 1
            logger.warning("  ✗ Rejected: %s", result.quality_report.get("reject_reason"))

        # Save per-subject quality report
        report_path = os.path.join(DEMO_OUT_DIR, f"{sid}_quality_report.json")
        with open(report_path, "w") as f:
            json.dump(result.quality_report, f, indent=2, default=str)

        summary["results"].append(entry)

    summary["total_time_s"] = round(time.time() - t0, 3)
    summary["acceptance_rate"] = (
        summary["accepted"] / summary["subjects_attempted"]
        if summary["subjects_attempted"] > 0 else 0.0
    )

    # Save demo summary
    summary_path = os.path.join(DEMO_OUT_DIR, "demo_summary.json")
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2, default=str)

    logger.info(
        "\nDemo complete: %d/%d accepted (%.0f%%) in %.2f s",
        summary["accepted"],
        summary["subjects_attempted"],
        100 * summary["acceptance_rate"],
        summary["total_time_s"],
    )
    logger.info("Outputs written to: %s", DEMO_OUT_DIR)
    logger.info("REMINDER: All images are synthetic random-pixel fixtures, NOT real data.")

    return summary


if __name__ == "__main__":
    run_demo()
